# Generated by Django 5.2.8 on 2025-12-02 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long URL', max_length=2048)),
                ('short_code', models.CharField(db_index=True, help_text='Unique short code for the URL', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this URL', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this URL is currently active')),
                ('user', models.ForeignKey(blank=True, help_text='User who created this short URL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the visitor', null=True)),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL (where the visitor came from)', max_length=2048, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string (browser/device information)', null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.ForeignKey(help_text='The shortened URL that was clicked', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='urls.url')),
            ],
            options={
                'verbose_name': 'Click',
                'verbose_name_plural': 'Clicks',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'url'], name='urls_click_timesta_379a1c_idx')],
            },
        ),
    ]
