# Generated by Django 5.2.8 on 2026-01-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_alter_url_original_url_alter_url_short_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this QR code', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fill_color', models.CharField(default='#000000', max_length=7)),
                ('back_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('box_size', models.PositiveIntegerField(default=10)),
                ('url', models.ForeignKey(help_text='The URL this QR code points to', on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='urls.url')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
