# Generated by Django 5.2.8 on 2026-01-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0003_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
